### ISSUE TITLE
Missing detailed error message on 500 response

### ISSUE THREAD

**Issue by yujunz** [tj/gobinaries#31] opened 2020-06-26 03:17 UTC
## Prerequisites

* [x] I searched to see if the issue already exists.

## Description

Got `Error downloading, got 500 response from server` but don't know what went wrong exactly.
## Steps to Reproduce

```
curl -sf https://gobinaries.com/juicedata/juicesync | sh

  ==> Downloading github.com/juicedata/juicesync@master
  ==> Resolved version master to v0.1.0
  ==> Downloading binary for darwin amd64

  Error downloading, got 500 response from server
```

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by mblarsen** [comment] 2020-06-26 03:20
Possible duplicate of #25

**Comment by tj** [comment] 2020-06-26 08:51
closing just for the dup, but looks like this error is 

```
building: exit status 1: go: github.com/juicedata/juicesync@v0.1.0 requires
	qiniupkg.com/x@v7.0.7+incompatible: reading qiniupkg.com/x/go.mod at revision v7.0.7: unknown revision v7.0.7
```

not exactly sure what that means hahah, I guess that v7.0.7 wasn't published?

**Closed as completed** 2020-06-26 08:52 UTC

**Comment by yujunz** [comment] 2020-06-26 08:56
Interesting. It was built successfully in travis with various go versions. https://travis-ci.com/github/juicedata/juicesync/builds/145093083
